#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By HTTP response header
sudo apt update -y
sudo apt install nginx -y
sudo sed -i "/listen 80 default_server/a add_header X-Served-By \"$(hostname)\";" /etc/nginx/sites-available/default
sudo service nginx restart
