#!/usr/bin/env bash
# Configures Nginx with a custom 404 page that contains "Ceci n'est pas une page"
sudo apt update -y
sudo apt install nginx -y
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
                return 301 https://github.com/Umutoni2;
        }

        location / {
                try_files \$uri \$uri/ =404;
        }

        error_page 404 /404.html;

        location = /404.html {
                internal;
        }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
